In [6]:
# 스크리너에서 수집한 종목코드, 종목명 데이터를 가져옵니다.
# 데이터 로드
import pandas as pd

df = pd.read_csv('nasdaq_screener_20260412.csv', na_filter=False)
df.head(3)

# 전처리
# df[df['Symbol'].str.contains(r'[^a-zA-X0-9-_/^ ]', regex=True)]
df['id'] = df['Symbol'].str.strip().replace(r'[/^]', '_', regex=True)
dict = df.to_dict(orient='records')

# stock_search() test

In [7]:
from dotenv import load_dotenv
import os

load_dotenv()
MEILISEARCH_MASTER_KEY = os.environ['MEILISEARCH_MASTER_KEY']

In [11]:
from meilisearch import Client

client = Client("http://127.0.0.1:7700", MEILISEARCH_MASTER_KEY)

client.index('nasdaq').add_documents(dict, primary_key='id')

TaskInfo(task_uid=0, index_uid='nasdaq', status='enqueued', type='documentAdditionOrUpdate', enqueued_at=datetime.datetime(2026, 4, 12, 12, 54, 1, 966838))

In [8]:
from meilisearch import Client
client = Client("http://127.0.0.1:7700", MEILISEARCH_MASTER_KEY)

#종목 모드 검색
def stock_search(query: str):
    
    result = client.index('nasdaq').search(
        query,
        {'attributesToSearchOn': ['Symbol', 'Name']}
    )
    
    if (result['estimatedTotalHits']) :
        print (result['estimatedTotalHits'])
        return result['hits'][:10] # 10개 이내로 
    else :
        return []

In [10]:
result = stock_search("apple")
# result = stock_search("INVALID-TICKER")
result

9

[{'id': 'AAPL',
  'Symbol': 'AAPL',
  'Name': 'Apple Inc. Common Stock',
  'Last Sale': '$260.48',
  'Net Change': -0.01,
  '% Change': '-0.004%',
  'Market Cap': '3824143347200.00',
  'Country': 'United States',
  'IPO Year': '1980',
  'Volume': 31258020,
  'Sector': 'Technology',
  'Industry': 'Computer Manufacturing'},
 {'id': 'APLE',
  'Symbol': 'APLE',
  'Name': 'Apple Hospitality REIT Inc. Common Shares',
  'Last Sale': '$12.48',
  'Net Change': 0.08,
  '% Change': '0.645%',
  'Market Cap': '2945850249.00',
  'Country': 'United States',
  'IPO Year': '2015',
  'Volume': 2893247,
  'Sector': 'Real Estate',
  'Industry': 'Real Estate Investment Trusts'},
 {'id': 'AAOI',
  'Symbol': 'AAOI',
  'Name': 'Applied Optoelectronics Inc. Common Stock',
  'Last Sale': '$150.60',
  'Net Change': 17.3,
  '% Change': '12.978%',
  'Market Cap': '11324941840.00',
  'Country': 'United States',
  'IPO Year': '2013',
  'Volume': 21854437,
  'Sector': 'Technology',
  'Industry': 'Semiconductors'},
 {'id': 'AIT',
  'Symbol': 'AIT',
  'Name': 'Applied Industrial Technologies Inc. Common Stock',
  'Last Sale': '$289.01',
  'Net Change': 2.6,
  '% Change': '0.908%',
  'Market Cap': '10780778184.00',
  'Country': 'United States',
  'IPO Year': '',
  'Volume': 256750,
  'Sector': 'Consumer Discretionary',
  'Industry': 'Industrial Specialties'},
 {'id': 'AMAT',
  'Symbol': 'AMAT',
  'Name': 'Applied Materials Inc. Common Stock',
  'Last Sale': '$399.49',
  'Net Change': 1.68,
  '% Change': '0.422%',
  'Market Cap': '317039205768.00',
  'Country': 'United States',
  'IPO Year': '1972',
  'Volume': 6397402,
  'Sector': 'Technology',
  'Industry': 'Semiconductors'},
 {'id': 'APLD',
  'Symbol': 'APLD',
  'Name': 'Applied Digital Corporation Common Stock',
  'Last Sale': '$26.26',
  'Net Change': 0.69,
  '% Change': '2.698%',
  'Market Cap': '7504308094.00',
  'Country': 'United States',
  'IPO Year': '2022',
  'Volume': 26311216,
  'Sector': 'Finance',
  'Industry': 'Finance: Consumer Services'},
 {'id': 'APP',
  'Symbol': 'APP',
  'Name': 'Applovin Corporation Class A Common Stock',
  'Last Sale': '$391.38',
  'Net Change': 12.24,
  '% Change': '3.228%',
  'Market Cap': '132003863640.00',
  'Country': 'United States',
  'IPO Year': '2021',
  'Volume': 4840413,
  'Sector': 'Technology',
  'Industry': 'Computer Software: Programming Data Processing'},
 {'id': 'SAIC',
  'Symbol': 'SAIC',
  'Name': 'Science Applications International Corporation Common Stock',
  'Last Sale': '$91.72',
  'Net Change': -2.94,
  '% Change': '-3.106%',
  'Market Cap': '3982419388.00',
  'Country': 'United States',
  'IPO Year': '',
  'Volume': 614722,
  'Sector': 'Technology',
  'Industry': 'EDP Services'},
 {'id': 'ILAG',
  'Symbol': 'ILAG',
  'Name': 'Intelligent Living Application Group Inc. Ordinary Shares',
  'Last Sale': '$3.55',
  'Net Change': 0.0,
  '% Change': '0.00%',
  'Market Cap': '7374940.00',
  'Country': 'Hong Kong',
  'IPO Year': '2022',
  'Volume': 8612,
  'Sector': 'Consumer Discretionary',
  'Industry': 'Office Equipment/Supplies/Services'}]

In [ ]:
 # 종목 기본정보 스크래핑
import yfinance as yf
import pandas as pd   

symbol = "AAPL"
# symbol = "INVALID-TICKER"
ticker = yf.Ticker(symbol)

print("-" * 50)
print("info:", len(ticker.info), ticker.info)
# if not ticker.info:  # 또는 len(ticker.info) < 2
#     print("유효하지 않은 티커입니다.")
# else :
#     print(ticker.info['longName'])

# keys_to_keep = ['longName','industry','sector','marketCap','sharesOutstanding']

# sub_dict = {key: ticker.info[key] for key in keys_to_keep if key in ticker.info}

# sub_dict

--------------------------------------------------
info: 182 {'address1': 'One Apple Park Way', 'city': 'Cupertino', 'state': 'CA', 'zip': '95014', 'country': 'United States', 'phone': '(408) 996-1010', 'website': 'https://www.apple.com', 'industry': 'Consumer Electronics', 'industryKey': 'consumer-electronics', 'industryDisp': 'Consumer Electronics', 'sector': 'Technology', 'sectorKey': 'technology', 'sectorDisp': 'Technology', 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers exclusive original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.', 'fullTimeEmployees': 150000, 'companyOfficers': [{'maxAge': 1, 'name': 'Mr. Timothy D. Cook', 'age': 64, 'title': 'CEO & Director', 'yearBorn': 1961, 'fiscalYear': 2025, 'totalPay': 16759518, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Kevan  Parekh', 'age': 53, 'title': 'Senior VP & CFO', 'yearBorn': 1972, 'fiscalYear': 2025, 'totalPay': 4034174, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Sabih  Khan', 'age': 58, 'title': 'Senior VP & Chief Operating Officer', 'yearBorn': 1967, 'fiscalYear': 2025, 'totalPay': 5021905, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': "Ms. Deirdre  O'Brien", 'age': 58, 'title': 'Senior Vice President of Retail & People', 'yearBorn': 1967, 'fiscalYear': 2025, 'totalPay': 5037867, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Katherine L. Adams', 'age': 61, 'title': 'Senior VP of Government Affairs & Secretary', 'yearBorn': 1964, 'fiscalYear': 2025, 'totalPay': 5022482, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Ben  Borders', 'age': 44, 'title': 'Principal Accounting Officer', 'yearBorn': 1981, 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Suhasini  Chandramouli', 'title': 'Director of Investor Relations', 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Jennifer G. Newstead J.D.', 'age': 54, 'title': 'Senior VP & General Counsel', 'yearBorn': 1971, 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Kristin Huguet Quayle', 'title': 'Vice President of Worldwide Communications', 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Greg  Joswiak', 'title': 'Senior Vice President of Worldwide Marketing', 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}], 'auditRisk': 2, 'boardRisk': 1, 'compensationRisk': 7, 'shareHolderRightsRisk': 1, 'overallRisk': 1, 'governanceEpochDate': 1775001600, 'compensationAsOfEpochDate': 1767139200, 'irWebsite': 'http://investor.apple.com/', 'executiveTeam': [], 'maxAge': 86400, 'priceHint': 2, 'previousClose': 260.49, 'open': 259.95, 'dayLow': 259.0231, 'dayHigh': 262.19, 'regularMarketPreviousClose': 260.49, 'regularMarketOpen': 259.95, 'regularMarketDayLow': 259.0231, 'regularMarketDayHigh': 262.19, 'dividendRate': 1.04, 'dividendYield': 0.4, 'exDividendDate': 1770595200, 'payoutRatio': 0.1304, 'fiveYearAvgDividendYield': 0.51, 'beta': 1.109, 'trailingPE': 33.013943, 'forwardPE': 27.971819, 'volume': 27978507, 'regularMarketVolume': 27978507, 'averageVolume': 47088316, 'averageVolume10days': 40018490, 'averageDailyVolume10Day': 40018490, 'bid': 260.2, 'ask': 260.63, 'bidSize': 1, 'askSize': 2, 'marketCap': 3828515864576, 'nonDilutedMarketCap': 3824143347200, 'fiftyTwoWeekLow': 189.81, 'fiftyTwoWeekHigh': 288.62, 'allTimeHigh': 288.62, 'allTimeLow': 0.049107, 'priceToSalesTrailing12Months': 8.78872, 'fiftyDayAverage': 260.8774, 'twoHundredDayAverage': 250.63445, 'trailingAnnualDividendRate': 1.03, 'trailingAnnualDividendYield': 0.0039540865, 'currency': 'USD', 'tradeable': False, 'enterpriseValue': 3847745437696, 'profitMargins': 0.27037, 'floatShares': 14656035251, 'sharesOutstanding': 14681140000, 'sharesShort': 129553812, 'sharesShortPriorMonth': 133373267, 'sharesShortPreviousMonthDate': 1770940800, 'dateShortInterest': 1773360000, 'heldPercentInsiders': 0.01641, 'heldPercentInstitutions': 0.65293, 'shortRatio': 3.17, 'shortPercentOfFloat': 0.0085, 'impliedSharesOutstanding': 14697926000, 'bookValue': 5.998, 'priceToBook': 43.42781, 'lastFiscalYearEnd': 1758931200, 'nextFiscalYearEnd': 1790467200, 'mostRecentQuarter': 1766793600, 'earningsQuarterlyGrowth': 0.159, 'netIncomeToCommon': 117776998400, 'trailingEps': 7.89, 'forwardEps': 9.31223, 'lastSplitFactor': '4:1', 'lastSplitDate': 1598832000, 'enterpriseToRevenue': 8.833, 'enterpriseToEbitda': 25.165, '52WeekChange': 0.28619397, 'SandP52WeekChange': 0.26099288, 'lastDividendValue': 0.26, 'lastDividendDate': 1770595200, 'quoteType': 'EQUITY', 'currentPrice': 260.48, 'targetHighPrice': 350.0, 'targetLowPrice': 205.0, 'targetMeanPrice': 296.3305, 'targetMedianPrice': 300.0, 'recommendationMean': 1.89583, 'recommendationKey': 'buy', 'numberOfAnalystOpinions': 40, 'totalCash': 66907000832, 'totalCashPerShare': 4.557, 'ebitda': 152901992448, 'totalDebt': 90509000704, 'quickRatio': 0.845, 'currentRatio': 0.974, 'totalRevenue': 435617005568, 'debtToEquity': 102.63, 'revenuePerShare': 29.305, 'returnOnAssets': 0.24377, 'returnOnEquity': 1.5202099, 'grossProfits': 206157004800, 'freeCashflow': 106312753152, 'operatingCashflow': 135471996928, 'earningsGrowth': 0.183, 'revenueGrowth': 0.157, 'grossMargins': 0.47325, 'ebitdaMargins': 0.35099998, 'operatingMargins': 0.35374, 'financialCurrency': 'USD', 'symbol': 'AAPL', 'language': 'en-US', 'region': 'US', 'typeDisp': 'Equity', 'quoteSourceName': 'Nasdaq Real Time Price', 'triggerable': True, 'customPriceAlertConfidence': 'HIGH', 'marketState': 'CLOSED', 'epsTrailingTwelveMonths': 7.89, 'epsForward': 9.31223, 'epsCurrentYear': 8.52255, 'priceEpsCurrentYear': 30.563625, 'fiftyDayAverageChange': -0.3973999, 'fiftyDayAverageChangePercent': -0.0015233204, 'twoHundredDayAverageChange': 9.845566, 'twoHundredDayAverageChangePercent': 0.03928257, 'sourceInterval': 15, 'exchangeDataDelayedBy': 0, 'averageAnalystRating': '1.9 - Buy', 'cryptoTradeable': False, 'hasPrePostMarketData': True, 'firstTradeDateMilliseconds': 345479400000, 'postMarketChangePercent': 0.19962722, 'postMarketPrice': 261.0, 'postMarketChange': 0.519989, 'regularMarketChange': -0.009979248, 'regularMarketDayRange': '259.0231 - 262.19', 'fullExchangeName': 'NasdaqGS', 'averageDailyVolume3Month': 47088316, 'fiftyTwoWeekLowChange': 70.67001, 'fiftyTwoWeekLowChangePercent': 0.37231976, 'fiftyTwoWeekRange': '189.81 - 288.62', 'fiftyTwoWeekHighChange': -28.139984, 'fiftyTwoWeekHighChangePercent': -0.09749839, 'fiftyTwoWeekChangePercent': 28.619396, 'dividendDate': 1770854400, 'earningsTimestamp': 1777579200, 'earningsTimestampStart': 1777579200, 'earningsTimestampEnd': 1777579200, 'earningsCallTimestampStart': 1777582800, 'earningsCallTimestampEnd': 1777582800, 'isEarningsDateEstimate': False, 'corporateActions': [], 'postMarketTime': 1775865589, 'regularMarketTime': 1775851202, 'shortName': 'Apple Inc.', 'longName': 'Apple Inc.', 'regularMarketChangePercent': -0.0038309526, 'regularMarketPrice': 260.48, 'exchange': 'NMS', 'messageBoardId': 'finmb_24937', 'exchangeTimezoneName': 'America/New_York', 'exchangeTimezoneShortName': 'EDT', 'gmtOffSetMilliseconds': -14400000, 'market': 'us_market', 'esgPopulated': False, 'displayName': 'Apple', 'trailingPegRatio': 2.3314}

In [28]:
ticker.quarterly_income_stmt

,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31
Tax Effect Of Unusual Items,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Tax Rate For Calcs,1.750000e-01,1.627240e-01,1.640000e-01,1.550000e-01,1.470000e-01
Normalized EBITDA,5.406600e+10,3.555400e+10,3.103200e+10,3.225000e+10,4.591200e+10
Net Income From Continuing Operation Net Minority Interest,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10
Reconciled Depreciation,3.214000e+09,3.127000e+09,2.830000e+09,2.661000e+09,3.080000e+09
Reconciled Cost Of Revenue,7.452500e+10,5.412500e+10,5.031800e+10,5.049200e+10,6.602500e+10
EBITDA,5.406600e+10,3.555400e+10,3.103200e+10,3.225000e+10,4.591200e+10
EBIT,5.085200e+10,3.242700e+10,2.820200e+10,2.958900e+10,4.283200e+10
Normalized Income,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10
Net Income From Continuing And Discontinued Operation,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10
Total Expenses,9.290400e+10,7.003900e+10,6.583400e+10,6.577000e+10,8.146800e+10
Total Operating Income As Reported,5.085200e+10,3.242700e+10,2.820200e+10,2.958900e+10,4.283200e+10
Diluted Average Shares,1.481036e+10,1.486361e+10,1.494818e+10,1.505613e+10,1.515086e+10
Basic Average Shares,1.474816e+10,1.481531e+10,1.490289e+10,1.499408e+10,1.508172e+10
Diluted EPS,2.840000e+00,1.850000e+00,1.570000e+00,1.650000e+00,2.400000e+00
Basic EPS,2.850000e+00,1.850000e+00,1.570000e+00,1.650000e+00,2.410000e+00
Diluted NI Availto Com Stockholders,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10
Net Income Common Stockholders,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10
Net Income,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10
Net Income Including Noncontrolling Interests,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10
Net Income Continuous Operations,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10
Tax Provision,8.905000e+09,5.338000e+09,4.597000e+09,4.530000e+09,6.254000e+09
Pretax Income,5.100200e+10,3.280400e+10,2.803100e+10,2.931000e+10,4.258400e+10
Other Income Expense,1.500000e+08,3.770000e+08,-1.710000e+08,-2.790000e+08,-2.480000e+08
Other Non Operating Income Expenses,1.500000e+08,3.770000e+08,-1.710000e+08,-2.790000e+08,-2.480000e+08
Operating Income,5.085200e+10,3.242700e+10,2.820200e+10,2.958900e+10,4.283200e+10
Operating Expense,1.837900e+10,1.591400e+10,1.551600e+10,1.527800e+10,1.544300e+10
Research And Development,1.088700e+10,8.866000e+09,8.866000e+09,8.550000e+09,8.268000e+09
Selling General And Administration,7.492000e+09,7.048000e+09,6.650000e+09,6.728000e+09,7.175000e+09
Gross Profit,6.923100e+10,4.834100e+10,4.371800e+10,4.486700e+10,5.827500e+10
Cost Of Revenue,7.452500e+10,5.412500e+10,5.031800e+10,5.049200e+10,6.602500e+10
Total Revenue,1.437560e+11,1.024660e+11,9.403600e+10,9.535900e+10,1.243000e+11
Operating Revenue,1.437560e+11,1.024660e+11,9.403600e+10,9.535900e+10,1.243000e+11

In [ ]:
ticker.quarterly_income_stmt.loc[
            ['Total Revenue','Gross Profit','Operating Income','Net Income']
        ].rename_axis('항목').rename(columns=lambda x: x.strftime("%Y-%m-%d"))

,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31
항목,,,,,
Total Revenue,1.437560e+11,1.024660e+11,9.403600e+10,9.535900e+10,1.243000e+11
Gross Profit,6.923100e+10,4.834100e+10,4.371800e+10,4.486700e+10,5.827500e+10
Operating Income,5.085200e+10,3.242700e+10,2.820200e+10,2.958900e+10,4.283200e+10
Net Income,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10

In [45]:
ticker.quarterly_income_stmt.loc[['Total Revenue','Gross Profit','Operating Income','Net Income']]

,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31
Total Revenue,1.437560e+11,1.024660e+11,9.403600e+10,9.535900e+10,1.243000e+11
Gross Profit,6.923100e+10,4.834100e+10,4.371800e+10,4.486700e+10,5.827500e+10
Operating Income,5.085200e+10,3.242700e+10,2.820200e+10,2.958900e+10,4.283200e+10
Net Income,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10

In [57]:
ticker.quarterly_income_stmt.loc[
            ['Total Revenue','Gross Profit','Operating Income','Net Income']
        ].rename_axis('항목').rename(columns=lambda x: x.strftime("%Y-%m-%d")).to_dict()

{'2025-12-31': {'Total Revenue': 143756000000.0,
  'Gross Profit': 69231000000.0,
  'Operating Income': 50852000000.0,
  'Net Income': 42097000000.0},
 '2025-09-30': {'Total Revenue': 102466000000.0,
  'Gross Profit': 48341000000.0,
  'Operating Income': 32427000000.0,
  'Net Income': 27466000000.0},
 '2025-06-30': {'Total Revenue': 94036000000.0,
  'Gross Profit': 43718000000.0,
  'Operating Income': 28202000000.0,
  'Net Income': 23434000000.0},
 '2025-03-31': {'Total Revenue': 95359000000.0,
  'Gross Profit': 44867000000.0,
  'Operating Income': 29589000000.0,
  'Net Income': 24780000000.0},
 '2024-12-31': {'Total Revenue': 124300000000.0,
  'Gross Profit': 58275000000.0,
  'Operating Income': 42832000000.0,
  'Net Income': 36330000000.0}}

In [76]:
a = ticker.quarterly_income_stmt.loc[
            ['Total Revenue','Gross Profit','Operating Income','Net Income']].rename_axis('항목').rename(columns=lambda x: x.strftime("%Y-%m-%d"))
a

,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31
항목,,,,,
Total Revenue,1.437560e+11,1.024660e+11,9.403600e+10,9.535900e+10,1.243000e+11
Gross Profit,6.923100e+10,4.834100e+10,4.371800e+10,4.486700e+10,5.827500e+10
Operating Income,5.085200e+10,3.242700e+10,2.820200e+10,2.958900e+10,4.283200e+10
Net Income,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10

In [77]:
df = a.reset_index()
df.to_dict('records')

[{'항목': 'Total Revenue',
  '2025-12-31': 143756000000.0,
  '2025-09-30': 102466000000.0,
  '2025-06-30': 94036000000.0,
  '2025-03-31': 95359000000.0,
  '2024-12-31': 124300000000.0},
 {'항목': 'Gross Profit',
  '2025-12-31': 69231000000.0,
  '2025-09-30': 48341000000.0,
  '2025-06-30': 43718000000.0,
  '2025-03-31': 44867000000.0,
  '2024-12-31': 58275000000.0},
 {'항목': 'Operating Income',
  '2025-12-31': 50852000000.0,
  '2025-09-30': 32427000000.0,
  '2025-06-30': 28202000000.0,
  '2025-03-31': 29589000000.0,
  '2024-12-31': 42832000000.0},
 {'항목': 'Net Income',
  '2025-12-31': 42097000000.0,
  '2025-09-30': 27466000000.0,
  '2025-06-30': 23434000000.0,
  '2025-03-31': 24780000000.0,
  '2024-12-31': 36330000000.0}]

In [80]:

bal = ticker.quarterly_balance_sheet.loc[
            ['Total Assets','Total Liabilities Net Minority Interest','Stockholders Equity']
        ].rename_axis('항목').rename(columns=lambda x: x.strftime("%Y-%m-%d"))

bal = bal.iloc[:, :5]
bal

,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31
항목,,,,,
Total Assets,3.792970e+11,3.592410e+11,3.314950e+11,3.312330e+11,3.440850e+11
Total Liabilities Net Minority Interest,2.911070e+11,2.855080e+11,2.656650e+11,2.644370e+11,2.773270e+11
Stockholders Equity,8.819000e+10,7.373300e+10,6.583000e+10,6.679600e+10,6.675800e+10